version: '3.4'

services:
  doccure_database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=doccure
      - POSTGRES_DB=Doccure
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - doccure

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=doccure@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=doccure
    ports:
      - '5050:80'
    restart: unless-stopped
    volumes:
      - pgadmin:/root/.pgadmin
    depends_on:
      - doccure_database
    networks:
      - doccure

volumes:
  database-data:
  pgadmin:

networks:
  doccure:
    driver: bridge
