version: '3.4'

services:
  doccure_database:
    image: postgres:latest
    container_name: doccure_database
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=doccure
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - doccure

  api:
    image: ${DOCKER_REGISTRY-}api
    container_name: api
    command: dotnet watch run
    build:
      context: ../../../
      dockerfile: Api/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
      - 'ConnectionStrings__DefaultConnection=Server=doccure_database;Port=5432;Database=Doccure;User ID=admin;Password=doccure;SSL Mode=Disable;Trust Server Certificate=true;'
    ports:
      - '5000:5000'
    depends_on:
      - doccure_database
    restart: on-failure
    networks:
      - doccure

volumes:
  database-data:

networks:
  doccure:
    driver: bridge
