version: '3.4'

services:
  doccure_database:
    image: postgres:latest
    container_name: ${CONTAINER_NAME_PREFIX}_doccure_database
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=doccure
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - ${CONTAINER_NAME_PREFIX}

  app:
    build:
      context: ../../../
      dockerfile: Api/Dockerfile
    container_name: ${CONTAINER_NAME_PREFIX}_app
    env_file:
      - ./.env
    volumes:
      - ~/.aspnet/https:/https:ro
      - ../../../:/app
    ports:
      - '5000:5000'
      - '5001:5001'
    depends_on:
      - doccure_database
    working_dir: /app/Api
    command: dotnet watch run --urls=https://+:5001;http://+:5000
    restart: on-failure
    networks:
      - ${CONTAINER_NAME_PREFIX}

volumes:
  database-data:

networks:
  backend:
    driver: bridge
